# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c672f07dcde637b5823b83e5cd23cdd9ed20b44b629cdee26aae5c0cb6e251be02642ec18f28370f9e1582240611a40851b27573df27e28202225c9c7741afb9

test:
  secret_key_base: 96474706a8cd9a23ab28bd311322cb16b7fa2fc2a59bd78bddf0dcd5414d6f38928ceaa693b3219f211f867bacd40b601e5a8b5e9605bc628ac4f82a3d90c146

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
